### ISSUE TITLE
Token Says Audio on Condition Added or Removed Broken

### ISSUE THREAD

**Issue by Ssezra** [napolitanod/Token-Says#68]
Prior configured tokens will still play audio but any new configured audio settings will not play. (When conditions are added or removed) The console provides this error when trying to play audio given an action.
TypeError: Cannot read properties of null (reading 'id')
[Detected 3 packages: token-says, dfreds-convenient-effects, midi-qol]
    at helpers.js:14:109
    at EmbeddedCollection.find (collection.mjs:46:12)
    at activeEffectToWorkflowData (helpers.js:14:91)
    at index.js:160:26
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at ClientDatabaseBackend.callback (foundry.js:10105:13)
    at foundry.js:10075:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleCreateEmbeddedDocuments (foundry.js:10075:33)
    at ClientDatabaseBackend._createEmbeddedDocuments (foundry.js:9967:17)
    at async Function.createDocuments (document.mjs:338:21)
    at async EffectHandler.addEffect (effect-handler.js:110:5)
    at async EffectHandler.toggleEffect (effect-handler.js:30:9)
    at async checkWounded (patching.js:716:5)
    at async Actor5e._preUpdateActor (patching.js:736:3)
    at async ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:10203:7)
    at async ClientDatabaseBackend._updateDocuments (foundry.js:10122:22)
    at async Function.updateDocuments (document.mjs:373:21)
    at async Actor5e.update (document.mjs:456:21)

**Comment by Ssezra** [comment]
After a little more testing, this error only appears if token says is enabled. If dfreds and midi both display this error if token says is enabled and trying to play audio through an action.

**Comment by napolitanod** [comment]
Hmmm - I think this may be caused by a token somewhere on the scene not having an actor association given the line number and file of the error. I couldn't get it to trigger myself on a new audio rule for add or remove effect so I am thinking it may be that. If I am understanding your report, this occurs in 1.8.4 also and regardless of other modules.

Here is a candidate release fix - when you have a sec can you please try to install this and see if it addresses the error?
https://github.com/napolitanod/Token-Says/releases/download/1.9.01/module.json

**Comment by Ssezra** [comment]
Installed the release fix but I still receive the following errors in the console.
Foundry VTT | Error thrown in hooked function '' for hook 'createActiveEffect'
_call @ foundry.js:297
callAll @ foundry.js:253
callback @ foundry.js:10105
(anonymous) @ foundry.js:10075
_handleCreateEmbeddedDocuments @ foundry.js:10075
_createEmbeddedDocuments @ foundry.js:9967
await in _createEmbeddedDocuments (async)
create @ backend.mjs:95
await in create (async)
createDocuments @ document.mjs:338
createEmbeddedDocuments @ document.mjs:522
addEffect @ effect-handler.js:110
toggleEffect @ effect-handler.js:30
await in toggleEffect (async)
_executeLocal @ socketlib.js:192
executeAsGM @ socketlib.js:90
toggleEffect @ effect-interface.js:114
onToggleEffect @ status-effects.js:62
🎁TokenHUD.prototype._onToggleEffect#dfreds-convenient-effects @ main.js:56
🎁call_wrapper @ libWrapper-wrapper.js:620
🎁TokenHUD.prototype._onToggleEffect#0 @ libWrapper-wrapper.js:189
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:319 TypeError: Cannot read properties of null (reading 'id')
[Detected 2 packages: token-says, dfreds-convenient-effects]
    at helpers.js:14:109
    at EmbeddedCollection.find (collection.mjs:46:12)
    at activeEffectToWorkflowData (helpers.js:14:91)
    at index.js:160:26
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at ClientDatabaseBackend.callback (foundry.js:10105:13)
    at foundry.js:10075:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleCreateEmbeddedDocuments (foundry.js:10075:33)
    at ClientDatabaseBackend._createEmbeddedDocuments (foundry.js:9967:17)
    at async Function.createDocuments (document.mjs:338:21)
    at async EffectHandler.addEffect (effect-handler.js:110:5)
    at async EffectHandler.toggleEffect (effect-handler.js:30:9)

**Comment by Ssezra** [comment]
This is with no modules turned on other then token says. Adding a condition or removing a condition will not execute audio and will send these errors to the console. all other audio actions work. This is for a newly created token.

**Comment by Ssezra** [comment]
It has something to do with link actor data. If i unlink the actor data on a token the condition audio works again.

**Comment by napolitanod** [comment]
Thank you for trying. The error is occurring where I put in a check that should fix that error to my knowledge. Have you tried this on other scenes? I'm thinking that it isn't the new actor that is the problem, but the scene containing another token where that token doesn't have any actor in the world (the token was added but then the actor deleted). But that is just a guess from where the error is occurring and likely wrong. 

I'm just not able to reproduce it and I'm trying different things out as well as the steps you've provided. I'll let you know once I hit on it. I pushed out the fix that didn't work for you so you will see an update for 1.9.1 go out.

**Comment by napolitanod** [comment]
I've not had luck recreating. Can you please try going to the scene where this error is occuring, doing F12 to show the browser's developer console, and then within the console line add `canvas.scene.tokens.find(t => t.actor.id === "test")` and hit enter to run it? I want to see if this triggers the same error.
